//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Virtual Robot.rc
//
#define IDOK2                           2
#define IDOK3                           3
#define IDOK4                           4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DESIGNTYPE                  129
#define ID_INDICATOR_COORD              129
#define IDR_VIEW                        130
#define ID_INDICATOR_TOOL               130
#define IDS_LINE                        131
#define IDS_SNAP                        132
#define IDS_GRID                        133
#define IDR_SET                         134
#define IDS_MODEL                       134
#define IDS_SIMULATION                  135
#define IDR_SIM                         136
#define IDS_ONLINE                      136
#define IDS_STRUCTURE                   137
#define LOGO                            139
#define TEST                            140
#define NAVIG                           141
#define PROGBAR                         142
#define LIGHT                           143
#define MAT                             144
#define GEOMETRY                        145
#define SURFACE                         147
#define ROBOTICS                        149
#define IDB_SPLASH                      151
#define IDR_NETWORK                     155
#define IDR_COMBOBAR                    157
#define PROGBAREX                       159
#define IDD_FWD                         160
#define IDD_INV                         161
#define IDB_THEORY                      162
#define DHC                             163
#define LINK                            164
#define EDITING                         165
#define IDC_EDIT1                       1004
#define IDC_EDIT2                       1005
#define IDC_EDIT3                       1006
#define IDC_EDIT4                       1007
#define IDC_EDIT5                       1008
#define IDC_EDIT6                       1009
#define IDC_BUTTON1                     1010
#define IDC_BUTTON2                     1011
#define IDC_SLIDER1                     1015
#define IDC_SLIDER2                     1016
#define IDC_COMBO1                      1017
#define IDC_SLIDER3                     1017
#define IDC_COMBO2                      1018
#define IDC_RICHEDIT1                   1018
#define TOP                             32771
#define BOTTOM                          32772
#define FRONT                           32773
#define BACK                            32774
#define LEFT                            32775
#define RIGHT                           32776
#define ORTHO                           32777
#define ZOOMI                           32778
#define ID_BUTTON32779                  32779
#define ZOOMO                           32779
#define SOLID                           32781
#define WIRE                            32782
#define UNDO                            32783
#define REDO                            32784
#define ORTHO1                          32786
#define ORTHO2                          32787
#define ORTHO3                          32788
#define PAN                             32789
#define ROTATE                          32790
#define POINTER                         32791
#define LIGHTS                          32792
#define MATERIAL                        32793
#define ROBOT                           32794
#define COORDINATESYSTEM                32795
#define PROGRAM                         32796
#define DESIGN                          32797
#define SIMSET                          32798
#define RESTORE                         32800
#define RULER                           32801
#define STOP                            32802
#define PAUSE                           32803
#define GO                              32804
#define STEP_F                          32805
#define STEP_B                          32806
#define RESET                           32807
#define LINETOOL                        32808
#define POLYLINE                        32811
#define ARC                             32812
#define CIRCLE                          32813
#define ELLIPSE                         32814
#define SPLINE                          32815
#define POINTTOOL                       32817
#define PRIZMATIC                       32818
#define SPHERICAL                       32819
#define CHLINDER                        32820
#define CONE                            32821
#define TORUS                           32822
#define EXTRUDE                         32823
#define REVOLVE                         32824
#define SLICE                           32825
#define SECTION                         32826
#define INTERSECTION                    32827
#define BZSURF                          32828
#define EDGESURF                        32829
#define RULESURF                        32830
#define REVOL                           32831
#define PRIZ                            32833
#define WAY4                            32835
#define ENDEFFECTOR                     32836
#define WAY2                            32837
#define WAY                             32838
#define SNAP1                           32839
#define SNAP2                           32840
#define ISNAP                           32842
#define SNAP4                           32843
#define LENGTH                          32844
#define DIA                             32845
#define ANGLE                           32846
#define LABEL                           32847
#define TEXTBOX                         32848
#define SCANIT                          32849
#define RASTER                          32850
#define DIGITIZER                       32852
#define ID_VIEW_SIM_BAR                 32853
#define ID_VIEWS                        32854
#define ID_SETTINGS_BAR                 32855
#define ID_SURFACES_VIEW                32856
#define ID_GEOM_TOOLS                   32857
#define ID_ROBOTICS_VIEW                32858
#define ID_VIEW_NAVIG                   32860
#define ID_VIEW_CODEEDITOR              32861
#define ID_CLIENTCONFIG                 32862
#define ID_SERVER_SETTING               32863
#define ID_CONNECT                      32864
#define ID_VIEW_NETWORK                 32867
#define ID_VIEW_PROGRESS                32868
#define NET_DISCONNECT                  32869
#define CONTINUOUS_ORBIT                32870
#define VIEW_THE_POINTS                 32871
#define VIEW_NET_WIZARD                 32872
#define DO_SUSPEND_NET                  32873
#define DO_DENY                         32874
#define VIEW_NETSTATS                   32875
#define ID_START_SIM                    32876
#define IDSTARTONLINE                   32877
#define IDCSTOPONLINE                   32878
#define ED1                             32879
#define ED2                             32880
#define ED3                             32881
#define ED4                             32882
#define ED5                             32883
#define ED6                             32884
#define ED7                             32885
#define VIEW_GRID_THING                 32886

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32887
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
