// Robot.h: interface for the CRobot class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_ROBOT_H__B098DB80_A275_11D7_811C_F82806C10000__INCLUDED_)
#define AFX_ROBOT_H__B098DB80_A275_11D7_811C_F82806C10000__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CRobot  
{
public:
	CRobot();
	virtual ~CRobot();

};

#endif // !defined(AFX_ROBOT_H__B098DB80_A275_11D7_811C_F82806C10000__INCLUDED_)
